### PR TITLE
Suggested Content Improvements for the English Pages

### PR DESCRIPTION
**Pull request by sjmclean24**
It seems that the English part of the website has been done using an automatic translation service.

I have done the first round of suggested content improvements to the English Pages.

Have also converted contact number reference in the translation file so that it's centrally managed, as well as added the link of type tel as it was missing in some places.

### CODE REVIEW

**Comment by anneke** [comment]
I've sent this proposal through to our content manager, if she gives her OK I will give you a heads' up! I can then also resolve the conflicts if needed.

**Review by anneke — APPROVED** [review]
Checked these with the content manager and all are approved! 👍

**Comment by anneke** [comment]
I do notice some merge issues - could you help with this @sjmclean24 ?

**Comment by sjmclean24** [comment]
@anneke I have solved the conflicts.

Can you please check?

Thanks!

**Pull request merged**
