### PR TITLE
patch for multiple translation (en) errors

### PR DESCRIPTION
**Pull request by jsoeterbroek**
Patch for multiple translation (en) errors.

### CODE REVIEW

**Comment by jsoeterbroek** [comment]
Please review

**Comment by bwbroersma** [comment]
Looks good to me, but I lost the merge rights on this repo.
BTW there is currently also a paid front-end work [being done](https://github.com/mellewynia/nl-covid19-notification-app-website/tree/feature/design-v0.6-texts) for v0.6.

**Comment by jsoeterbroek** [comment]
@EdoPlantinga: please (review and) merge

**Comment by mellewynia** [comment]
Thanks. It is looking good. Will merge

**Pull request merged**
