### PR TITLE
Mailto Usability Improvement

### PR DESCRIPTION
**Pull request by sjmclean24**
By appending the subject line, we ease the user from having to think about the subject line and can focus on the message.

If unchanged, it also gives a clear indication to the recepient of the email on the context of the email message from the subject itself.

A rule based system could also be created for such emails to be forwarded as required, or placed in a particular folder, helping the recepient who has to process the Corona Melder inbox.

Used the translations.yml to set the EN and NL translation strings, so that they can be centrally modified and added as needed.

### CODE REVIEW

**Comment by anneke** [comment]
Hi @sjmclean24 , looks to me like a great addition! We'll have to run content changes like these by someone from communications, but we'll get back to this PR this week.

We require every commit to be signed, this means installing the following guides:

- https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key
- https://docs.github.com/en/github/authenticating-to-github/adding-a-new-gpg-key-to-your-github-account
- https://docs.github.com/en/github/authenticating-to-github/telling-git-about-your-signing-key

If you use software for Git (like me), this software might need seperate setup. I use Git Tower on a Mac, and needed to update to the latest version so I could tell the program to use GPG correctly.

Let me know if you need help with this, I am also on the Code4NL Slack where you can ping me :)

**Comment by sjmclean24** [comment]
@anneke thanks for the above information.

The last commit with ID 389c17f should be as required. However, I read that the base branch requires all commits to be signed.

Can you verify if my latest commit is fine? And should I proceed to re-open a new PR ensuring that all commits are Verified and Signed with the GPG Key (in which case this PR would be close)?

Let me know as I have some other feature branches I'm waiting to create a PR for :)

**Comment by anneke** [comment]
Yes, the last commit went perfectly! 
A trick @hidde told me about was to do an interactive rebase on this branch and edit the branch names (adding a space will suffice), this will generate new hashes for each commit, so you can push them signed and verified! :) 
Let me know if there's anything I can do to help.

**Comment by sjmclean24** [comment]
I have resubmitted this feature in PR #284

**Pull request closed without merging**
