### PR TITLE
patch for issue #40 - minimal layout 404 page

### PR DESCRIPTION
**Pull request by jsoeterbroek**
patch for issue #40 - minimal layout 404 page

### CODE REVIEW

**Comment by jsoeterbroek** [comment]
Please review

**Comment by jsoeterbroek** [comment]
@mellewynia : please review

**Comment by mellewynia** [comment]
Ziet er goed uit! Neem ik mee, als basis voor normale (single) content pagina

**Comment by mellewynia** [comment]
- https://minvws.github.io/nl-covid19-notification-app-website/404
- https://minvws.github.io/nl-covid19-notification-app-website/500

**Comment by EdoPlantinga** [comment]
@mellewynia can this one be closed?

**Pull request merged**
